[[apologetics]]
= Apologetics
:date:

== Introduction
What is an apologia?

The word apologia makes a bold appearance in **1 Peter 3:15**.
Paul addresses early Christians in Asia Minor who were going through intense suffering and persecution because of their faith in Christ.

[quote, 1 Peter 3:15, The Apostle Peter writing to Christians in Asia Minor ]
____
__14__ But even if you should suffer for righteousness’ sake, you will be blessed. Have no fear of them, nor be troubled, __15__ but in your hearts honor Christ the Lord as holy, always being prepared to make a **defense(ἀπολογία)** to anyone who asks you for a reason for the hope that is in you; yet do it with **gentleness and respect**, __16__ having a good conscience, so that, when you are slandered, those who revile your good behavior in Christ may be put to shame.
____

== Word Meaning
In Greek the word **ἀπολογία** means "A speech of defense, defense, reply"

For example: "hear the defense which I now make to you"

This word is used several times throughout the New Testament and refers to a defense against examination in court and a defense and confirmation of the gospel message itself.

A few prime examples would be:

[quote, Acts 22:1, ἀπολογία study]
____
“Brothers and fathers, **hear the defense** that I now make before you.”
____

[quote, Acts 25:16, ἀπολογία study]
____
I answered them that it was not the custom of the Romans to give up anyone before the accused met the accusers face to face and **had opportunity to make his defense** concerning the charge laid against him.
____
[quote, Colossians 9:3, ἀπολογία study]
____
This is my defense to those who would examine me.
____
[quote, Philippians 1:7, ἀπολογία study]
____
It is right for me to feel this way about you all, because I hold you in my heart, for you are all partakers with me of grace, both in my imprisonment and in the **defense and confirmation of the gospel**.
____